CREATE TABLE DEPT(
    DEPTNO NUMBER(2),
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);

INSERT INTO DEPT
VALUES(10, 'ACCOUNTING', 'NEW YORK');

INSERT INTO DEPT
VALUES(20, 'RESEARCH', 'DALLAS');

INSERT INTO DEPT
VALUES(30, 'SALES', 'CHICAGO');

INSERT INTO DEPT
VALUES(40, 'OPERATIONS', 'BOSTON');

COMMIT;